### PR TITLE
Movie details and search functionality

### PR DESCRIPTION
**Pull request by Marianna-Weychan**
I'm still working on tweaking the MovieDetails and Search files to make them work. Unfortunately, I had technical problems on this branch, so I will close it and create a new one.

### CODE REVIEW

**Comment by ghost** [comment]
the conflict is caused by the fact that I moved HAshRouter from index.jd to App.js because I saw that some of you commented like that and I thought it would be better but I'm also waiting for your opinion :)

**Review by KatarzynaZaloba — APPROVED** [review]
I saw during our conversarion that this component is working, so I give an approve. Gla to see we are so close to finish project 😄

**Comment by ghost** [comment]
I am glad that the component works and I am curious how it will interact with our application!

**Review by AdrianJar — APPROVED** [review]
Good job Marianna as we discussed and tried to figure out how to do it. It works ! Great job!

**Comment by ghost** [comment]
Thank you, I'm glad that my idea worked, although I still need to refine this logic, but for now, let's see how it will work in our application!

**Pull request merged**
