### PR TITLE
Added RWD to app

### PR DESCRIPTION
**Pull request by AdrianJar**
I hope it works well I tried to copy 1:1 from figma :)

### CODE REVIEW

**Review by KatarzynaZaloba — APPROVED** [review]
Seems legit!

**Review by KatarzynaZaloba — APPROVED** [review]

**Review by KatarzynaZaloba — APPROVED** [review]
I see mediaquerry here, so as far ok

**Review by KatarzynaZaloba — APPROVED** [review]
Good as far

**Review by KatarzynaZaloba — APPROVED** [review]
Nice job!

**Review by KatarzynaZaloba — APPROVED** [review]
Very nice!

**Review by KatarzynaZaloba — APPROVED** [review]
Great job!

**Review by Marianna-Weychan — APPROVED** [review]

**Comment by ghost** [comment]
There are media queries so it's starting to look great.
Good job Adrian!
I also added MQ to Header, please have a look at my code and I'm waiting for your review :)

**Pull request merged**
