### PR TITLE
Movie detailss

### PR DESCRIPTION
**Pull request by Marianna-Weychan**
ok I added the Loading component and made some cosmetic fixes in the files.
Please check if Loading is well implemented logically

### CODE REVIEW

**Review by KatarzynaZaloba — APPROVED** [review]
We got it!
image

**Comment by ghost** [comment]
Okay best team!
I am sending the built Search and MovieDetails components.
In addition, in terms of their operation, I made changes to App.js, rootSaga.js, store.js and routes.js.
Please take a moment to look at my code and check if my logic and implementation are correct :)

**Comment by ghost** [comment]
@KatarzynaZaloba (regarding Loading) 
yes but I don't know why the text: "Search results for..." is not displayed :/
I implemented this and it worked for me initially

**Review by AdrianJar — APPROVED** [review]
Nice job, now we can use loading animation for movies without text.
And nice we have now search!

**Pull request merged**
