### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by Marianna-Weychan**
I created a navigation branch, I'm doing this pull to test if everything works for me compatible with your projects :)

### CODE REVIEW

**Comment by KatarzynaZaloba** [comment]
As I can see there is ony adding files, so I can approve.

**Review by KatarzynaZaloba — APPROVED** [review]
let's merge - the template of the files for Navication is confirmed by me
@AdrianJar , could you please check and submit review?

**Review by AdrianJar — APPROVED** [review]
Looks good!

**Comment by ghost** [comment]
yes, so far I only added the files themselves to see if the change was made correctly to this repository, because before I had something wrong and they didn't want to leave

**Comment by ghost** [comment]
Chyba się udało zmergować, jak zakomituję w plikach co nieco kodu to spróbujemy zrobić bardziej skomplikowany merge

**Comment by ghost** [comment]
hahaha I wrote it instinctively in Polish :)

**Pull request merged**
