### PR TITLE
added ogimage

### PR DESCRIPTION
**Pull request by KatarzynaZaloba**
I've added ogimage
image

It's better than nothing :D

### CODE REVIEW

**Review by AdrianJar — APPROVED** [review]
Very nice idea with this OG

**Comment by KatarzynaZaloba** [comment]
I changed it. I think this one is more professional.
What do you think?
ogimage
but I realized there are watermarks :smile: I will take care of it tomorrow

**Comment by KatarzynaZaloba** [comment]
now I am happy :smile:
image

**Review by Marianna-Weychan — APPROVED** [review]
oh yeeeeah
It's extra! It's nice that you added Kualalumpur, great Kasia!

**Pull request merged**
