### PR TITLE
Feature/pagination with api

### PR DESCRIPTION
**Pull request by KatarzynaZaloba**
Hi!
I am happy to say that I've connected finally Pagination to the Popular People list.
I used the same logic to the Movielist, but it's not working somehow...
@AdrianJar  @Marianna-Weychan do you have any idea how to connect it together?

image

### CODE REVIEW

**Comment by ghost** [comment]
Hmm, I think that pagination must be added to each feature component, i.e. not to the App but to MovieList, MovieDetails, PeopleList and PeopleDetails as a footer. I don't have an idea of ​​the logic behind it yet, but I'll think about it.
I think that useQueryParameter and a hook that will subtract or add one page depending on which useQueryParam returns or use useSearchParam can be helpful here?
 const [searchParams, setSearchParams] = useSearchParams(); from "react-router-dom" ?

**Comment by AdrianJar** [comment]
Maybe use of useState? This maybe would work?

**Comment by KatarzynaZaloba** [comment]
I connected Pagination with API, so I can click and see the number of page... but... still doesn't connect with Movielist :joy: 
Can I say it's progress? :satisfied:
image

**Comment by KatarzynaZaloba** [comment]
I'm almost there!

image

**Comment by KatarzynaZaloba** [comment]
@AdrianJar can I ask you to check by yourself? I don;t want to mess with your component so far. I see I cannot somehow achieve it...

**Comment by AdrianJar** [comment]
Great job! I will look at it and try to help with it!

**Review by AdrianJar — APPROVED** [review]
Together we managed to make it work! A lot of job done with a little help of me and we are again closer and closer to finishing it! You nailed this task!

**Comment by ghost** [comment]
I am impressed Kasia and of course Adrian!
Pagination terrified me and I probably wouldn't be able to handle it on my own, but the most important thing is that we can count on each other and that's what a group project is all about! Our application has more and more functionalities and I hope that soon everything will work together :)

**Review by Marianna-Weychan — APPROVED** [review]

**Pull request merged**
