### PR TITLE
Feature/people5

### PR DESCRIPTION
**Pull request by KatarzynaZaloba**
I've added data from themoviedb to the PersonDetails component.
Looks like it's working, so we can manage MovieDetails like this.
ezgif-4-47f52598dd

### CODE REVIEW

**Comment by KatarzynaZaloba** [comment]
Things to do related this component:

- [ ] responsivness (did I use correct word?) for all components in PersonDetails,
- [x] Link from MovieTile to the MovieDetails page,
- [x] correct Loading component while opening new page,
- [x] Error component while there is an error,
- [x] change that silly hyperlink colour with Styled-Components,
- [ ] and maybe we can limit records to few only? What do you think?

**Review by Marianna-Weychan — APPROVED** [review]
wonderfully! Well done!
I can't find the reason why my MovieDetails is not showing up so maybe your component can help me!

**Comment by ghost** [comment]
what is a stupid color?

**Review by AdrianJar — APPROVED** [review]
This is huge work done! Nothing else I can say! Great job!

**Pull request merged**
