### PR TITLE
Feature/NoResults

### PR DESCRIPTION
**Pull request by KatarzynaZaloba**
I've added the new component - No Results. It's only in CSS now.

### CODE REVIEW

**Comment by KatarzynaZaloba** [comment]
@AdrianJar @Marianna-Weychan 
Dear, we need to check and merge pulls as soon as it possible - on Mon/Tue there is another code review. Just saying :sweat_smile:

**Review by AdrianJar — APPROVED** [review]
Great job. Keep it up!

**Comment by ghost** [comment]
Definitely Kasia, you're right, we need to connect everything because we have a lot of components and when they are not connected, our application looks undeveloped :D
But your work is great!

**Review by Marianna-Weychan — APPROVED** [review]
I have no objections, approve!

**Pull request merged**
